version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - python3-hivex
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
      - PATH="/home/docs/.local/bin:$PATH" poetry config virtualenvs.create false
    post_install:
      - PATH="/home/docs/.local/bin:$PATH" poetry install --with=dev
      - pip install sphinx_rtd_theme
sphinx:
  configuration: docs/source/conf.py
