name: Run Radon

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install project dependencies
        run: |
          poetry install --with=dev

      - name: Run radon
        run: |
          poetry run radon cc -s -a snr
