name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Install payload build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git make clang lld nasm
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec

      - name: Remove local parts from version
        run: |
          sed -i 's/+git//' pyproject.toml

      - name: Build payloads
        run: |
          chmod +x tools/build_payloads.sh
          ./tools/build_payloads.sh

      - name: Install project dependencies
        run: |
          poetry install

      - name: Build the project
        run: |
          poetry build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
