name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install payload build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git make clang lld nasm
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
      

      - name: Remove local parts from version
        run: |
          sed -i 's/+git//' pyproject.toml

      - name: Build payloads
        run:  |
          chmod +x tools/build_payloads.sh
          ./tools/build_payloads.sh
        
      - name: Install project dependencies
        run: |
          poetry install

      - name: Build the project
        run: |
          poetry build

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $TWINE_PASSWORD
          poetry publish
