name: Run mypy

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec

      - name: Install project dependencies
        run: |
          poetry install --with=dev

      - name: Run mypy
        run: |
          poetry run mypy --strict -p snr || true
